sculpin_content_types:
    # Need to explicitly disable it
    posts:
        enabled: false

    guides:
        permalink: documentation/guides/:slug_title.html

    libraries:
        permalink: documentation/libraries/:slug_title.html

    references:
        permalink: documentation/references/:slug_title.html

sculpin_markdown:
    parser_class: Sculpin\Bundle\MarkdownBundle\PhpMarkdownExtraParser